CREATE TABLE QUIZ_FORM
(

    QUESTION_ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUESTION         VARCHAR(255) NOT NULL,
    OPTION1          VARCHAR(255) NOT NULL,
    OPTION2          VARCHAR(255) NOT NULL,
    OPTION3          VARCHAR(255) NOT NULL,
    OPTION4          VARCHAR(255) NOT NULL,
        CORRECTANSWER    INT NOT NULL

);