CREATE TABLE QUIZ_FORM
(
    ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
    QUESTION         VARCHAR(255) NOT NULL,
    OPTIONS          VARCHAR(255) NOT NULL,
        CORRECTANSWERINDEX    INT(1) NOT NULL

);